### ISSUE TITLE
Error executing ‘postInstallation’: EEXIST: file already exists, symlink ‘/bitnami/wordpress/wp-content’ -> ‘/opt/bitnami/wordpress/wp-content

### ISSUE THREAD

**Issue by jfeliweb** [bitnami/bitnami-docker-wordpress-nginx#40] opened 2021-01-26 22:43 UTC
Hi! 
I am running into an error when trying to run my custom image
``Error executing ‘postInstallation’: EEXIST: file already exists, symlink ‘/bitnami/wordpress/wp-content’ -> ‘/opt/bitnami/wordpress/wp-content’``

I followed the same blog post and created a **download-extra.sh**
```
#!/bin/bash
set -e

# Start removing Bitnami Default Plugins
rm -rf /opt/bitnami/wordpress/wp-content/plugins/akismet/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/all-in-one-seo-pack/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/all-in-one-wp-migration/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/wp-cloud-mgmt-console/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/google-analytics-for-wordpress/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/jetpack/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/simple-tags/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/amp/
rm -rf /opt/bitnami/wordpress/wp-content/plugins/wordpress-mu-domain-mapping/
rm -f /opt/bitnami/wordpress/wp-content/plugins/hello.php

# Start removing Default Themes
rm -rf /opt/bitnami/wordpress/wp-content/themes/twenty*

# Grab and Install Fracture Core Plugin and Theme
curl -sL -C - -H 'Authorization: token <token>' https://github.com/github/core-plugin/archive/1.0.zip -o /tmp/core-plugin.zip
curl -sL -C - -H 'Authorization: token <token>' https://github.com/github/theme/archive/1.0.zip -o /tmp/theme.zip

unzip /tmp/core-plugin.zip -d /opt/bitnami/wordpress/wp-content/plugins
mv -f /opt/bitnami/wordpress/wp-content/plugins/core-plugin-1.0 "/opt/bitnami/wordpress/wp-content/plugins/core-plugin/"
unzip /tmp/theme.zip -d /opt/bitnami/wordpress/wp-content/themes
mv -f /opt/bitnami/wordpress/wp-content/themes/theme-1.0 "/opt/bitnami/wordpress/wp-content/themes/theme/"
rm -rf /tmp/core-plugin.zip
rm -rf /tmp/theme.zip

# Grab and install other plugins

curl -o /tmp/wordpress-seo.15.6.2.zip https://downloads.wordpress.org/plugin/wordpress-seo.15.6.2.zip
curl -o /tmp/stream.3.6.0.zip https://downloads.wordpress.org/plugin/stream.3.6.0.zip
curl -o /tmp/wp-redis.1.1.1.zip https://downloads.wordpress.org/plugin/wp-redis.1.1.1.zip
curl -o /tmp/jwt-auth.zip https://downloads.wordpress.org/plugin/jwt-auth.zip
curl -o /tmp/svg-support.2.3.18.zip https://downloads.wordpress.org/plugin/svg-support.2.3.18.zip
curl -o /tmp/user-switching.1.5.6.zip https://downloads.wordpress.org/plugin/user-switching.1.5.6.zip

unzip /tmp/wordpress-seo.15.6.2.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/stream.3.6.0.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/wp-redis.1.1.1.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/jwt-auth.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/svg-support.2.3.18.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/user-switching.1.5.6.zip -d /opt/bitnami/wordpress/wp-content/plugins

rm -rf /tmp/wordpress-seo.15.6.2.zip
rm -rf /tmp/stream.3.6.0.zip
rm -rf /tmp/wp-redis.1.1.1.zip
rm -rf /tmp/jwt-auth.zip
rm -rf /tmp/svg-support.2.3.18.zip
rm -rf /tmp/user-switching.1.5.6.zip

## S3 Uploads
curl -sL -C - -H 'Authorization: token <token>' https://github.com/humanmade/S3-Uploads/releases/download/2.2.1/manual-install.zip -o /tmp/manual-install.zip
unzip /tmp/manual-install.zip -d /opt/bitnami/wordpress/wp-content/plugins/s3-uploads/
rm -rf /tmp/manual-install.zip
```
As the blog post described I add the run command under `COPY rootfs / ` in the **Dockerfile**
```
RUN bash download-extra.sh
```
And I am activating the plugins in the app-entrypoint.sh
```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
    . /nginx-init.sh
    . /wordpress-init.sh
    nami_initialize php nginx mysql-client wordpress
    info "Starting gosu... "
    . /post-init.sh
fi

nami_initialize nginx php mysql-client wordpress
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate fracture_theme'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate fracture_core_plugin'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate jwt-auth'
#su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate s3-uploads'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate stream'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate svg-support'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate user-switching'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate w3-total-cache'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate wordpress-seo'
info "Starting wordpress... "

exec tini -- "$@"
```
Everything works fine locally but not when I add my custom image to the WordPress Helm Chart I am now getting this: 
```
Error executing ‘postInstallation’: EEXIST: file already exists, symlink ‘/bitnami/wordpress/wp-content’ -> ‘/opt/bitnami/wordpress/wp-content’
```
Any help or if I could get pointed in the right direction would be greatly appreciated.

**Comment by miguelaeh** [comment] 2021-01-27 09:23
Hi @jfeliweb ,
It seems that the symlink target already exists. I would say it is due to the volume data. If the volume is already initialized the symlink must point in the other direction, like `‘/opt/bitnami/wordpress/wp-content’` -> `‘/bitnami/wordpress/wp-content’`

**Comment by juan131** [comment] 2021-01-29 12:13
I'm closing this issue as a duplicate of https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/37
@jfeliweb please refer to the instructions I provide in the other issue.

**Closed by juan131** 2021-01-29 12:13 UTC
